# Yarn 4 Configuration for TalentSol Backend
# Local development setup with XGBoost integration

# Package manager settings
nodeLinker: node-modules
enableGlobalCache: true
enableTelemetry: false

# Local development paths
cacheFolder: .yarn/cache
globalFolder: .yarn/global
installStatePath: .yarn/install-state.gz
lockfileFilename: yarn.lock
pnpDataPath: .pnp.cjs
pnpUnpluggedFolder: .yarn/unplugged
virtualFolder: .yarn/virtual

# XGBoost specific settings
environmentVariables:
  XGBOOST_LOCAL_DEVELOPMENT: "true"
  PYTHON_PATH: "./ml-models/shared/venv/bin/python"
  VIRTUAL_ENV: "./ml-models/shared/venv"

# Development settings
preferInteractive: true
progressBarStyle: modern

# Network settings
httpTimeout: 60000
networkTimeout: 60000

# Plugin settings
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

# Workspace settings (if using workspaces)
workspaceFolder: .

# TypeScript and build settings
supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current

# Local package resolution
packageExtensions:
  "tsx@*":
    dependencies:
      "@types/node": "*"
  
# Development dependencies preferences
preferReuse: true
enableScripts: true
enableStrictSsl: true

# XGBoost Python integration
postinstall: |
  echo "🐍 Setting up Python virtual environment for XGBoost..."
  if [ ! -d "ml-models/shared/venv" ]; then
    python -m venv ml-models/shared/venv
    source ml-models/shared/venv/bin/activate
    pip install -r ml-models/decision-tree/requirements.txt
  fi
  echo "✅ Python environment ready"
