version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: talentsol_postgres
    environment:
      POSTGRES_DB: talentsol_ats
      POSTGRES_USER: talentsol_user
      POSTGRES_PASSWORD: talentsol_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
